vim.cmd.colorscheme("southernlights")
vim.cmd("hi Pmenu ctermfg=40 ctermbg=236")
vim.cmd("hi PmenuSel ctermbg=52")
vim.cmd("hi PmenuSbar ctermbg=4")
vim.cmd("hi EndingWhiteSpace ctermbg=52")
vim.cmd("match EndingWhiteSpace /\\s\\+\\%#\\@<!$/")
