vim.cmd.colorscheme("southernlights")
vim.cmd("hi Pmenu ctermfg=40 ctermbg=236 guifg=#00d700")
vim.cmd("hi PmenuSel ctermbg=52 guibg=#5f0000")
vim.cmd("hi PmenuSbar ctermbg=4 guibg=#00005f")
vim.cmd("hi Keyword ctermfg=193 guifg=#ffff5f")
vim.cmd("hi link jsonKeyword Keyword")
vim.cmd("hi Number	ctermfg=223	guifg=#ffb9a7")
vim.cmd("hi Include	ctermfg=219	cterm=NONE guifg=#ff00ff	gui=NONE")
vim.cmd("hi EndingWhiteSpace ctermbg=52 guibg=#5f0000")
vim.cmd [[match EndingWhiteSpace /\s\+\%#\@<!$/")]]
