version: '2'
issues:
  max-same-issues: 10
linters:
  default: all
  disable:
    - nlreturn
    - prealloc
    - nolintlint
    - lll
    - gomoddirectives
    - depguard
    - gosec
  settings:
    varnamelen:
      ignore-decls:
        - wg sync.WaitGroup
        - wg *sync.WaitGroup
        - h hash.Hash
    perfsprint:
      strconcat: false
