require('colorscheme.tokyonight')
require('plugins.packchanged')

require('plugins.ansible')
require('plugins.gitsigns')
require('plugins.diffview')
require('plugins.go')
require('plugins.c')
require('plugins.bash')
require('plugins.blink')
require('plugins.treesitter')
require('plugins.tmux-vim-navigator')
require('plugins.colorful-menu')
require('plugins.lua_ls')
require('plugins.fzf')
require('plugins.undotree')
require('plugins.oil')
require('plugins.rust')
require('plugins.python')
require('plugins.json')
require('plugins.luasnip')
require('plugins.toml')
require('plugins.yaml')
require('plugins.markdown')
require('plugins.neogit')
require('plugins.flash')

require('plugins.mini')

require('config.options')
require('config.keymaps')
require('config.autocmds')

-- vim.lsp.inlay_hint.enable(true, { bufnr = 0 })
vim.diagnostic.config({ virtual_text = true })
