require('colorscheme.tokyonight')

require('plugins.ansible')
require('plugins.gitsigns')
require('plugins.diffview')
require('plugins.go')
require('plugins.c')
require('plugins.bash')
require('plugins.blink')
require('plugins.treesitter')
require('plugins.tmux-vim-navigator')
require('plugins.colorful-menu')
require('plugins.lua_ls')
require('plugins.mini')
require('plugins.fzf')
require('plugins.undotree')
require('plugins.oil')
require('plugins.rust')
require('plugins.python')

require('config.options')
require('config.keymaps')
require('config.autocmds')

vim.lsp.inlay_hint.enable(true, { bufnr = 0 })
