require('colorscheme.tokyonight')
require('config.options')
require('plugins.fzf')

require('plugins.ansible')
require('plugins.bash')
require('plugins.blink')
require('plugins.c')
require('plugins.colorful-menu')
require('plugins.dap')
require('plugins.diffview')
require('plugins.flash')
require('plugins.flash')
require('plugins.gitsigns')
require('plugins.go')
require('plugins.json')
require('plugins.lua_ls')
require('plugins.luasnip')
require('plugins.markdown')
require('plugins.mini')
require('plugins.neogit')
require('plugins.oil')
require('plugins.opencode')
require('plugins.python')
require('plugins.rust')
require('plugins.tiny-cmdline')
require('plugins.tmux-vim-navigator')
require('plugins.toml')
require('plugins.treesitter')
require('plugins.undotree')
require('plugins.winresizer')
require('plugins.yaml')

require('config.keymaps')
require('config.autocmds')

vim.lsp.inlay_hint.enable(true, nil)
vim.diagnostic.config({ virtual_text = true })

vim.keymap.set('n', '<Leader>th', function() vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled(nil), nil) end,
  { noremap = true, desc = 'Toggle inlay hints' })
